#!/usr/bin/env bash

# Check script.log for  error logs. Pipefail set. No clobber set.
set -Eeuo pipefail
set -o noclobber
# exec >script.log 2>&1
exec 2>script.log



echo -e "\nThis error log is generated by custom.sh\n" >&2

# Konsave
konsave -i /media/DATA/SOFTWARE/Programming/KONSAVE/Monark.knsv
konsave -a Monark

# Install REN
PROJECT_DIR="/media/DATA/SOFTWARE/Programming/Projects"

sudo make -C "$PROJECT_DIR/REN" install

# Create /etc/environment
sudo mv -i environment /etc/

# Create sddm.conf
# sudo mv sddm.conf /etc/sddm.conf.d/cursor-theme.conf
sudo mv -i sddm.conf /etc/sddm.conf
