#!/usr/bin/env bash

# Check script.log for  error logs. Pipefail set. No clobber set.
set -Eeuo pipefail
set -o noclobber
# exec >script.log 2>&1
exec 2>script.log



echo -e "\nThis error log is generated by dev.sh\n" >&2

# Create AUR SSH keys.
touch ~/.ssh/aur.pub
touch ~/.ssh/aur
# Add the keys manually.

# Create ssh config
touch ~/.ssh/config
echo -e "Host aur.archlinux.org aur
HostName aur.archlinux.org
User aur
IdentityFile ~/.ssh/aur
IdentitiesOnly yes" > ~/.ssh/config

# Rust Toolchain
if ! command -v rustup >/dev/null 2>&1; then
    yay -S --noconfirm rustup
fi

rustup default stable
rustup component add rustfmt clippy

# Emacs
if ! command -v emacs >/dev/null 2>&1; then
    yay -S --noconfirm emacs
fi
git clone https://github.com/doomemacs/doomemacs ~/.config/emacs
~/.config/emacs/bin/doom install
~/.config/emacs/bin/doom sync

# Create autostart for emacs daemon
# Set permissions...first.
mv emacs_daemon.desktop ~/.config/autostart/
