#!/usr/bin/env bash

# Check script.log for  error logs. Pipefail set. No clobber set.
set -Eeuo pipefail
set -o noclobber
# exec >script.log 2>&1
exec 2>script.log



echo -e "\nThis error log is generated by packages.sh\n" >&2

install='clipgrab dropbox chromium  telegram-desktop  signal-desktop  whatsapp-for-linux haruna inkscape obs-studio img2pdf yt-dlp tagspaces-bin kamoso ghostwriter gsfonts ocenaudio-bin xaos youtube-music-desktop kdialog base-devel git tree update-grub reflector rsync curl ttf-jetbrains-mono gparted veracrypt keepassxc vim dolphin-plugins pavucontrol appimagelauncher nvidia-settings kde-applications ffmpegthumbs kdeplasma-addons qt6-imageformats stacer-bin nvidia-prime glxinfo virtualgl zip unzip unrar foremost bluez bluez-utils bluedevil ttf-meslo-nerd-font-powerlevel10k neofetch fastfetch lolcat taplo-cli jq cmatrix plasma6-applets-window-title plasma-applet-window-buttons ttf-ibm-plex konsave zsh zsh-theme-powerlevel10k procreate-thumbnailer-git rustup emacs just github-desktop-bin texstudio ollama'
remove='vi'
# packages from org file.

read -r -a install_pkgs <<< "$install"
read -r -a remove_pkgs  <<< "$remove"

if (( ${#install_pkgs[@]} )); then
  echo "Installing packages:"
  printf '  + %s\n' "${install_pkgs[@]}"
  yay -S --needed "${install_pkgs[@]}"
fi

if (( ${#remove_pkgs[@]} )); then
  echo "Removing packages:"
  printf '  - %s\n' "${remove_pkgs[@]}"
  yay -Rns "${remove_pkgs[@]}"
fi
